name: publish jar
on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Set version
        run: mvn versions:set -DnewVersion=${{ github.ref_name }}-SNAPSHOT
      - name: Publish package
        run: mvn -B clean deploy -DskipTests -DrepositoryId=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
